WebApi_Consumption/BooksMvc/Models/AuthorsViewModel.cs
using DataLayer.Models;
using System.Collections.Generic;

namespace BooksMvc.Models
{
    public class AuthorsViewModel
    {
        public List<Author> Authors { get; set; }
        public Book SelectedBook { get; set; }
    }
}

WebApi_Consumption/BooksMvc/Models/BooksViewModel.cs
using DataLayer.Models;
using System.Collections.Generic;

namespace BooksMvc.Models
{
    public class BooksViewModel
    {
        public List<Book> Books { get; set; }
        public Author SelectedAuthor { get; set; }
    }
}

WebApi_Consumption/BooksMvc/Models/EditBookViewModel.cs
using DataLayer.Models;
using System.Web.Mvc;

namespace BooksMvc.Models
{
    public class EditBookViewModel
    {
        public Book SelectedBook { get; set; }
        public SelectList AvailableAuthors { get; set; }

        public int SelectedAuthorId { get; set; }
    }
}

WebApi_Consumption/BooksMvc/Controllers/AuthorsController.cs
using BooksMvc.Models;
using DataLayer.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace BooksMvc.Controllers
{
    public class AuthorsController : BaseController
    {
        // GET: Authors
        [Route("/authors/{id}")]
        public ActionResult Index(int? id, int page = 1)
        {
            var authors = bookService.GetAuthors().Result;
            var books = bookService.GetBooks().Result;
            int itemsPerPage = 10;

            ViewBag.PageCount = Math.Ceiling(authors.Count() / (double)itemsPerPage);
            if (page < 0)
            {
                page = 0;
            }

            if (page > ViewBag.PageCount)
            {
                page = (int)ViewBag.PageCount;
            }

            ViewBag.CurrentPage = page;
            int start = (page - 1) * itemsPerPage;

            //for (int i = authors.Count; i < 150; i++)
            //{
            //    var aut = new Author()
            //    {
            //        Name = $"Example Author #{i.ToString()}",
            //        Books = new List<Book>()
            //    };
            //    authors.Add(aut);
            //}

            var vm = new AuthorsViewModel()
            {
                Authors = authors.Skip(start).Take(itemsPerPage).ToList(),
                SelectedBook = id == null ? null : books.Find(x => x.Id == id)
            };

            if (vm.SelectedBook != null)
            {
                vm.SelectedBook.Author = authors.Find(x => x.Id == vm.SelectedBook.AuthorId);
            }

            return View(vm);
        }

        public ActionResult Details(int id)
        {
            var author = bookService.GetAuthor(id).Result;
            author.Books = (bookService.GetBooks().Result).Where(bk => bk.AuthorId == author.Id).ToList();
            if (author != null)
            {
                return PartialView("_AuthorDetails", author);
            }

            return View("Error");
        }

        public ActionResult Create()
        {
            return PartialView("_CreateAuthor");
        }

        [HttpPost]
        public async Task<ActionResult> Create(Author model)
        {
            await bookService.CreateAuthor(model.Name);
            return RedirectToAction("Index");
        }
    }
}

WebApi_Consumption/BooksMvc/Controllers/BaseController.cs
using OrchestrationLayer;
using System.Web.Mvc;

namespace BooksMvc.Controllers
{
    public class BaseController : Controller
    {
        public BooksService bookService { get; } = new BooksService("http://localhost:51518/");
    }
}

WebApi_Consumption/BooksMvc/Controllers/BooksController.cs
using BooksMvc.Models;
using DataLayer.Models;
using OrchestrationLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Threading.Tasks;

namespace BooksMvc.Controllers
{
    public class BooksController : BaseController
    {
        // GET: Books
        public ActionResult Index(int? id)
        {
            var books = bookService.GetBooks().Result;
            var authors = bookService.GetAuthors().Result;

            foreach (var book in books)
            {
                book.Author = authors.Find(x => x.Id == book.AuthorId);
            }

            var vm = new BooksViewModel()
            {
                Books = books,
                SelectedAuthor = id == null ? null : authors.Find(x => x.Id == id)
            };

            return View(vm);
        }

        public ActionResult Edit(int id)
        {
            var book = bookService.GetBook(id).Result;
            var authors = bookService.GetAuthors().Result;
            var currentAuthor = authors.FirstOrDefault(x => x.Id == book.AuthorId);
            var viewModel = new EditBookViewModel()
            {
                AvailableAuthors = new SelectList(items: authors, dataTextField: "Name", dataValueField: "Id", selectedValue: authors.First(x => x.Id == book.AuthorId)),
                SelectedBook = book
            };
            
            

            if (viewModel.SelectedBook != null)
            {
                return View(viewModel);
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<ActionResult> Edit(EditBookViewModel model)
        {
            if (ModelState.IsValid)
            {
                var newAuthor = bookService.GetAuthor(model.SelectedAuthorId).Result;
                model.SelectedBook.Author = newAuthor;
                model.SelectedBook.AuthorId = model.SelectedAuthorId;
                await bookService.UpdateBook(model.SelectedBook);

                return RedirectToAction("Index");
            }

            return View(model);
        }

        public ActionResult Details(int id)
        {
            var book = bookService.GetBook(id).Result;
            book.Author = bookService.GetAuthor(book.AuthorId).Result;

            if (book != null)
            {
                return PartialView("_BookDetails", book);
            }

            return View("Error");
        }

        [HttpGet]
        public ActionResult Create()
        {
            var vm = new EditBookViewModel()
            {
                AvailableAuthors = new SelectList(bookService.GetAuthors().Result, "Id", "Name"),
                SelectedBook = new Book()
            };

            return PartialView("_CreateBook", vm);
        }

        [HttpPost]
        public async Task<ActionResult> Create(EditBookViewModel model)
        {
            var author = bookService.GetAuthor(model.SelectedAuthorId).Result;
            await bookService.CreateNewBookWithAuthor(author, model.SelectedBook.Name, model.SelectedBook.PublicationYear);
            return RedirectToAction("Index");
        }
    }
}

WebApi_Consumption/BooksMvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BooksMvc.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebApi_Consumption/BooksMvc/Views/Authors/Index.cshtml
@model BooksMvc.Models.AuthorsViewModel

@{
    ViewBag.Title = "Index";
    var aut = new DataLayer.Models.Author();
}

<h1>Authors</h1>
@*<p>
        @Ajax.ActionLink("Add", "Create", "Authors",
                                               null,
                                               new AjaxOptions
                                               {
                                                   InsertionMode = InsertionMode.Replace,
                                                   UpdateTargetId = "detailsPanel"
                                               },
                                               new { @class = "btn btn-info btn-xs"})

    </p>*@

@if (ViewBag.PageCount > 1)
{
    <ul class="pagination pagination-sm">

        <li class="@(ViewBag.CurrentPage > 1 ? "page-item" : "disabled")">
            <a href="@Url.Action("Index", new { page = ViewBag.CurrentPage > 1 ? ViewBag.CurrentPage - 1 : 1 })">&laquo;</a>
        </li>

        @for (int i = 1; i <= ViewBag.PageCount; i++)
        {
            string classes = i == ViewBag.CurrentPage ? "page-item active" : "page-item";

            <li class="@classes">
                <a class="page-link" href="@Url.Action("Index", new { page = i })">@i</a>
            </li>
        }

        <li class="@(ViewBag.CurrentPage < ViewBag.PageCount ? "page-item" : "disabled")">
            <a href="@Url.Action("Index", new { page = ViewBag.CurrentPage == ViewBag.PageCount ? ViewBag.CurrentPage : ViewBag.CurrentPage + 1 })">&raquo;</a>
        </li>
    </ul>
}


<div class="row">
    <div class="col-lg-7 col-md-7 col-sm-12" style="max-height:400px; overflow-y:auto">
        <table class="table table-hover">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => aut.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => aut.Books)
                </th>
            </tr>

            @foreach (var author in Model.Authors)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => author.Name)
                    </td>
                    <td>
                        @if (author.Books.Count != 0)
                        {
                            foreach (var book in author.Books)
                            {
                                <p>
                                    @Ajax.ActionLink(book.Name, "Details", "Books",
                                               new { id = book.Id },
                                               new AjaxOptions
                                               {
                                                   InsertionMode = InsertionMode.Replace,
                                                   UpdateTargetId = "detailsPanel"
                                               },
                                               new { style="text-decoration:none"})
                                </p>
                            }
                        }
                    </td>
                    <td>
                        @Ajax.ActionLink("Add Book", "Create", "Books",
                                       null,
                                       //new { id = book.Id },
                                       new AjaxOptions
                                       {
                                           InsertionMode = InsertionMode.Replace,
                                           UpdateTargetId = "detailsPanel"
                                       },
                                       new { @class = "btn btn-primary btn-xs"})

                    </td>
                </tr>
            }

        </table>

    </div>

    <div class="col-lg-5 col-md-5 col-sm-12" id="detailsPanel">

    </div>
</div>

@if (ViewBag.PageCount > 1)
{
    <ul class="pagination pagination-sm">

        <li class="@(ViewBag.CurrentPage > 1 ? "page-item" : "disabled")">
            <a href="@Url.Action("Index", new { page = ViewBag.CurrentPage > 1 ? ViewBag.CurrentPage - 1 : 1 })">&laquo;</a>
        </li>

        @for (int i = 1; i <= ViewBag.PageCount; i++)
        {
            string classes = i == ViewBag.CurrentPage ? "page-item active" : "page-item";

            <li class="@classes">
                <a class="page-link" href="@Url.Action("Index", new { page = i })">@i</a>
            </li>
        }

        <li class="@(ViewBag.CurrentPage < ViewBag.PageCount ? "page-item" : "disabled")">
            <a href="@Url.Action("Index", new { page = ViewBag.CurrentPage == ViewBag.PageCount ? ViewBag.CurrentPage : ViewBag.CurrentPage + 1 })">&raquo;</a>
        </li>
    </ul>
}


@section Scripts {
    @Scripts.Render("~/bundles/ajax")
}

WebApi_Consumption/BooksMvc/Views/Books/Edit.cshtml
@model BooksMvc.Models.EditBookViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Book</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SelectedBook.Id)

        <!-- TITLE -->
        <div class="form-group">
            @Html.LabelFor(model => model.SelectedBook.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SelectedBook.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SelectedBook.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <!-- PUBLICATION YEAR -->
        <div class="form-group">
            @Html.LabelFor(model => model.SelectedBook.PublicationYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SelectedBook.PublicationYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SelectedBook.PublicationYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <!-- AUTHOR -->
        <div class="form-group">
            @Html.LabelFor(model => new DataLayer.Models.Author().Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(
                    m => m.SelectedAuthorId,
                    Model.AvailableAuthors,
                    new { @class = "form-control"}
               )
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>

        @Html.HiddenFor(x => x.SelectedBook.AuthorId)
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApi_Consumption/BooksMvc/Views/Books/Index.cshtml
@model BooksMvc.Models.BooksViewModel

@{
    ViewBag.Title = "Books";
    var bk = new DataLayer.Models.Book();
}

<h2>Books</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div class="row">
    <div class="col-lg-8 col-md-8 col-sm-12">
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => bk.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => bk.Author)
                </th>
                <th>
                    @Html.DisplayNameFor(model => bk.PublicationYear)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model.Books)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Ajax.ActionLink(item.Author.Name, "Details", "Authors",
                                   new { id = item.Author.Id },
                                   new AjaxOptions
                                   {
                                       InsertionMode = InsertionMode.Replace,
                                       UpdateTargetId = "detailsPanel"
                                   },
                                   //new { @class = "btn btn-info btn-xs"})
                                   null )
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PublicationYear)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    </td>
                </tr>
            }

        </table>
    </div>

    <div class="col-lg-4 col-md-4 col-sm-12" id="detailsPanel">
        
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/ajax")
    }

WebApi_Consumption/BooksMvc/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebApi_Consumption/BooksMvc/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApi_Consumption/BooksMvc/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

WebApi_Consumption/BooksMvc/Views/Shared/_AuthorDetails.cshtml
@model DataLayer.Models.Author

<h3>@Model.Name</h3>
<h5>Books: (@Model.Books.Count())</h5>
<ul>
    @foreach (var book in Model.Books)
    {
        <li>@book.Name (@book.PublicationYear)</li>
    }
</ul>

WebApi_Consumption/BooksMvc/Views/Shared/_BookDetails.cshtml
@model DataLayer.Models.Book

<h3>@Model.Name</h3>
<h5>Author: @Html.ActionLink(Model.Author.Name, "Details", "Authors", new { id = Model.AuthorId }, null)</h5>
<p>@Html.DisplayNameFor(x => x.PublicationYear): 
@Html.DisplayFor(x => x.PublicationYear)</p>

WebApi_Consumption/BooksMvc/Views/Shared/_CreateAuthor.cshtml
@model DataLayer.Models.Author

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Add an author</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
                @Html.ActionLink("Cancel", "Index", null, htmlAttributes: new { @class = "btn btn-warning" })
            </div>
        </div>
    </div>
}

WebApi_Consumption/BooksMvc/Views/Shared/_CreateBook.cshtml
@model BooksMvc.Models.EditBookViewModel

@{
    ViewBag.Title = "_CreateBook";
}

<h2>Add a book</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SelectedBook.Id)

        <!-- TITLE -->
        <div class="form-group ">
            @Html.LabelFor(model => model.SelectedBook.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SelectedBook.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SelectedBook.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <!-- PUBLICATION YEAR -->
        <div class="form-group">
            @Html.LabelFor(model => model.SelectedBook.PublicationYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SelectedBook.PublicationYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SelectedBook.PublicationYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <!-- AUTHOR -->
        <div class="form-group">
            @Html.LabelFor(model => new DataLayer.Models.Author().Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(
                    m => m.SelectedAuthorId,
                    Model.AvailableAuthors,
                    
                    new { @class = "form-control", id = "authorsList"}
               )

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>

        @Html.HiddenFor(x => x.SelectedBook.AuthorId)
    </div>
}

WebApi_Consumption/BooksMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Books", "Index", "Books")</li>
                    <li>@Html.ActionLink("Authors", "Index", "Authors")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        @*<hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>